name: Machine Learning Pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: write

env:
  DOCKER_IMAGE_NAME: insurance-prediction-model # Ganti sesuai keinginan

jobs:
  ml_lifecycle:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Codebase
        uses: actions/checkout@v3

      - name: Initialize Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Prepare ML Libraries
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn

      - name: Execute MLflow Training
        run: |
          # Menjalankan project dari folder MLProject
          mlflow run MLProject --env-manager=local

      - name: Identify Metadata Run
        run: |
          # Mencari run_id terbaru dengan cara yang lebih ringkas
          LATEST_RUN=$(ls -t mlruns/0 | head -n 1)
          echo "MLFLOW_RUN_ID=$LATEST_RUN" >> $GITHUB_ENV
          echo "Identified Run ID: $LATEST_RUN"

      - name: Synchronize Artifacts to Repo
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Workflow Bot"
          git add mlruns/
          git commit -m "Auto-update: trained model artifacts [skip ci]" || exit 0
          git push

      - name: Containerize Model
        run: |
          # Build image menggunakan mlflow
          mlflow models build-docker --model-uri "runs:/${{ env.MLFLOW_RUN_ID }}/model" --name "${{ env.DOCKER_IMAGE_NAME }}"

      - name: Deploy to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish Docker Image
        run: |
          # Tagging dan Pushing dalam satu blok
          REPO_PATH=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
          docker tag ${{ env.DOCKER_IMAGE_NAME }} $REPO_PATH:latest
          docker tag ${{ env.DOCKER_IMAGE_NAME }} $REPO_PATH:${{ github.sha }}
          docker push $REPO_PATH --all-tags
