name: ML Pipeline CI

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  run-ml-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install MLflow & Dependencies
        run: |
          pip install mlflow pandas scikit-learn

      - name: Execute MLflow Project
        run: |
          # Menjalankan MLflow pada direktori MLProject
          mlflow run MLProject --env-manager=local

      - name: Extract Run ID
        run: |
          # Mengambil Run ID terbaru untuk keperluan Docker build
          NEW_ID=$(ls -t mlruns/0 | grep -v "meta.yaml" | head -n 1)
          echo "RUN_ID=$NEW_ID" >> $GITHUB_ENV

      - name: Save Artifacts to GitHub
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "MLflow Bot"
          git add mlruns/
          git commit -m "chore: save training artifacts [skip ci]" || exit 0
          git push

      - name: Build Model Container
        run: |
          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "insurance-app"

      - name: Push to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Finalize Image
        run: |
          FULL_IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/insurance-app:latest
          docker tag insurance-app $FULL_IMAGE_NAME
          docker push $FULL_IMAGE_NAME
