name: End-to-End ML Pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  training_and_deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install MLflow and Data Tools
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn

      - name: Run MLflow Project
        run: |
          # Pastikan perintah ini merujuk ke FOLDER MLProject
          # --env-manager=local digunakan agar tidak perlu membuat conda env baru di runner
          mlflow run MLProject --env-manager=local

      - name: Capture Newest Run ID
        run: |
          # Mengambil folder ID terbaru di dalam direktori mlruns/0
          LATEST_RID=$(ls -t mlruns/0 | grep -v "meta.yaml" | head -n 1)
          echo "RID=$LATEST_RID" >> $GITHUB_ENV
          echo "Targeting Run ID: $LATEST_RID"

      - name: Sync Artifacts to GitHub
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "Deployment Bot"
          git add mlruns/
          git commit -m "Auto-commit: Update model artifacts [skip ci]" || echo "No changes"
          git push

      - name: Generate Docker Image
        run: |
          # Build docker image menggunakan model dari run_id yang baru saja dibuat
          mlflow models build-docker --model-uri "runs:/${{ env.RID }}/model" --name "insurance-service"

      - name: Authenticate Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Image to Registry
        run: |
          # Tagging dengan username Docker Hub kamu
          DOCKER_REPO=${{ secrets.DOCKER_HUB_USERNAME }}/insurance-service
          docker tag insurance-service $DOCKER_REPO:latest
          docker push $DOCKER_REPO:latest
